### ISSUE TITLE
Platform Support x86_64 & aarch64

### ISSUE THREAD

**Issue by metaskills** [customink/crypteia#5]
Might have to change our Dockerfile around a bit if not Tier 1. More details here. https://doc.rust-lang.org/nightly/rustc/platform-support.html

**Comment by jhuiting** [comment]
@metaskills Any updates on the plans for `arm64`? Would add a lot of value to have both architectures supported. Really nice work on the extension, always was hoping that AWS made it this seamless to integrate secrets!

**Comment by jhuiting** [comment]
@metaskills I also didn't know but seems there's no native way to run ARM64 yet. But cross-compile seems to be easy like this based on cross (sample with the cross Github action: https://github.com/jhuiting/rust-cross-compile-test/blob/master/.github/workflows/build.yml).

**Comment by mattbajorek** [comment]
[cargo-lambda](https://www.cargo-lambda.info/guide/lambda-extensions.html) has worked for me to build for arm64 on Github actions for any Rust project. It uses [cargo-zigbuild](https://github.com/rust-cross/cargo-zigbuild) under the hood. I have not tried their lambda extensions though, which may be a better use case for this project.

For regular builds I would do:

```yaml
      - name: Install Cargo lambda
        run: pip3 install cargo-lambda

      - name: Cargo build
        run: cargo lambda build --release --arm64
```
