### ISSUE TITLE
Support Environments Updates & Bulk Fetches

### ISSUE THREAD

**Issue by metaskills** [customink/crypteia#7]
Right now the proof of concept will work as long as an existing ENV is set. For example, if `HELLO=yall` is set then the shared object hook into getenv can override that with `WORLD` as a value. But if `HELLO` were not set at all, then the current code will not return the override. Why is this important?

Let's say  you want to batch fetch many parameters using `ssm_parameters:/my/application/env` as a path. You could have something like this in your template.yml file:

```yaml
Globals:
  Function:
    Environment:
      Variables:
        X_CRYPTEIA_ENVIRONMENTS: ssm_parameters:/my/application/env
```

So this could pull in `DATABASE_URL`, `SECRET_KEY_BASE`, and many more. But would fail because there was no previous `DATABASE_URL` set. We could treat this as a feature and encourage placeholders like so, but that feels a bit superfluous? 

```yaml
Globals:
  Function:
    Environment:
      Variables:
        DATABASE_URL: placeholder
        SECRET_KEY_BASE: placeholder
        X_CRYPTEIA_ENVIRONMENTS: ssm_parameters:/my/application/env
```
